name: "Run rspec to execute tests"

env:
  RAILS_ENV: test
  POSTGRES_HOST: localhost
  POSTGRES_USERNAME: postgres
  POSTGRES_PASSWORD: postgres
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
        with:
          ruby-version: 3.2.0
          bundler-cache: true

      - name: Docker services
        run: docker-compose up -d

      - name: Set up application
        run: rake db:test:prepare

      - name: Run tests
        run: bundle exec rspec
